app: # project scope
  app_name: Chat Service
  app_version: 0.1.0-beta

database:
  driver: sqlite
  username: my_username
  password: my_password
  name: taveler
  host: localhost
  port: 5432
  timezone: UTC
  ssl_mode: false

hosts:
  - host: 192.168.6.199
    port: 8082
  - host: 127.0.0.1
    port: 8082


